source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'ReactiveCocoaApply_Tests' do
  pod "ReactiveCocoaApply", :path => "../"

  pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
end
