source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'ReactiveCocoaApply_Tests' do
  pod "ReactiveCocoaApply", :path => "../"

  pod 'ReactiveCocoa', '= 4.2.1'
  pod 'Quick', '~> 0.9.0'
  pod 'Nimble', '~> 4.1.0'
end
