source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'ReactiveCocoaApply_Tests', :exclusive => true do
  pod "ReactiveCocoaApply", :path => "../"

  pod 'ReactiveCocoa', '4.0.4-alpha-4'
  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '~> 3.0.0'
end
